# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemver < Formula
  desc "Git extension to easily manage your project's version based on Semantic Versioning and Conventional Commits"
  homepage "https://github.com/carlsberg/git-semver"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.2/git-semver_0.4.2_Darwin_x86_64.tar.gz"
      sha256 "a3565fc085b0950e9a382cf71d858efdeaaf1af4622fdd00209145d70971782d"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.2/git-semver_0.4.2_Darwin_arm64.tar.gz"
      sha256 "5498fcb3681cadd2792124cbba88882501e0acfb575a547fa367e3e3d557ae85"

      def install
        bin.install "git-semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.2/git-semver_0.4.2_Linux_x86_64.tar.gz"
      sha256 "5060b32d584820fc89bd7f65f672207d1c9098a5d5c2a4324af9bf52da7d99e5"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.2/git-semver_0.4.2_Linux_arm64.tar.gz"
      sha256 "7c6b56ec086523e604c9c838d983fb68b1ffdc3bb34ed1e4aac3c76fb5401309"

      def install
        bin.install "git-semver"
      end
    end
  end
end
