# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemver < Formula
  desc "Git extension to easily manage your project's version based on Semantic Versioning and Conventional Commits"
  homepage "https://github.com/carlsberg/git-semver"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.1/git-semver_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "68f92d1656a90efa31a6ff524ec79d82784a33609478d14c8bdd5ec1a2d2887a"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.1/git-semver_0.4.1_Darwin_arm64.tar.gz"
      sha256 "68f51b25b189866ab3f3c91acc3132737672061409db2059f96efc27a75e7a9b"

      def install
        bin.install "git-semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.1/git-semver_0.4.1_Linux_arm64.tar.gz"
      sha256 "0c0364bdc0d33c7b013a88239aaf075020772000bbe87565db409b07446d2de1"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.4.1/git-semver_0.4.1_Linux_x86_64.tar.gz"
      sha256 "76fad46b0837edf6836daf92c184da9cab5958aeb58cc3e53b41bc3d22df651a"

      def install
        bin.install "git-semver"
      end
    end
  end
end
