# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemver < Formula
  desc "Git extension to easily manage your project's version based on Semantic Versioning and Conventional Commits"
  homepage "https://github.com/carlsberg/git-semver"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.6.3/git-semver_0.6.3_Darwin_arm64.tar.gz"
      sha256 "649dd1d7ea355742896a8750d7bb6b5d3d5ab1183ec96e2eab427bba4d8fbabf"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.6.3/git-semver_0.6.3_Darwin_x86_64.tar.gz"
      sha256 "52220f067639b294aaefda92b855195ec004d2fa4969d6b86e5a833a395128f2"

      def install
        bin.install "git-semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.6.3/git-semver_0.6.3_Linux_arm64.tar.gz"
      sha256 "b5ff67035b642d06b35b6eae1ceab58a2c93ba9bfd707dc80d61806d2c09a6ce"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carlsberg/git-semver/releases/download/v0.6.3/git-semver_0.6.3_Linux_x86_64.tar.gz"
      sha256 "6090d70a28ab46df3135ced569c03a4e801600ce3faceb09e60a015db4c31872"

      def install
        bin.install "git-semver"
      end
    end
  end
end
